### ISSUE TITLE
Key error on login

### ISSUE THREAD

**Issue by MatthewJA** [ADACS-Australia/SS18A-JBanfield#13]
```
ERROR:django.request:Internal Server Error: /classify/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/alger/repos/SS18A-JBanfield/zooniverse_web/views/classify.py", line 110, in classify
    survey_id=request.session['survey_id'],
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__
    return self._session[key]
```

**Comment by MatthewJA** [comment]
But reloading the page makes it work fine! Curious.
